## tf.add, tf.matmul, tf.subtract, tf.Variable

In [1]:
import tensorflow as tf

2023-12-11 14:48:49.859476: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2023-12-11 14:48:49.859506: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.


In [2]:
# for making an array with one dimension with a special name we use tf.constannt
a = tf.constant([2], name = 'constant_a')
b = tf.constant([3], name = 'constant_b')

2023-12-11 14:48:52.457622: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2023-12-11 14:48:52.457663: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
2023-12-11 14:48:52.457698: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (mehran-Precision-Tower-3620): /proc/driver/nvidia/version does not exist
2023-12-11 14:48:52.458087: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [3]:
a,b

(<tf.Tensor: shape=(1,), dtype=int32, numpy=array([2], dtype=int32)>,
 <tf.Tensor: shape=(1,), dtype=int32, numpy=array([3], dtype=int32)>)

In [5]:
# for evaluating the value for the function we use this formation
a.numpy()[0]

2

In [13]:
# def add is used for adding two array
def add(a,b):
    c = tf.add(a,b)
    return c

In [12]:
result = add(a,b)
tf.print(result[0])

5


Define multidimensional arrays using tensorflow

In [14]:
scalar = tf.constant(2)
vector = tf.constant([1,2,3])
matrix = tf.constant([[1,2,3],[4,5,6],[7,8,9]])
tensor = tf.constant([[[1,2,3],[1,4,7],[2,5,8]],[[3,6,9],[2,5,8],[0,1,4]],[[2,5,8],[3,6,9],[2,5,4]]])

scalar, vector, matrix, tensor

(<tf.Tensor: shape=(), dtype=int32, numpy=2>,
 <tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>,
 <tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]], dtype=int32)>,
 <tf.Tensor: shape=(3, 3, 3), dtype=int32, numpy=
 array([[[1, 2, 3],
         [1, 4, 7],
         [2, 5, 8]],
 
        [[3, 6, 9],
         [2, 5, 8],
         [0, 1, 4]],
 
        [[2, 5, 8],
         [3, 6, 9],
         [2, 5, 4]]], dtype=int32)>)

In [15]:
scalar.shape, vector.shape, matrix.shape, tensor.shape

(TensorShape([]),
 TensorShape([3]),
 TensorShape([3, 3]),
 TensorShape([3, 3, 3]))

In [16]:
matrix_a = tf.constant([[1,2,3],[4,5,6],[7,8,9]])
matrix_b = tf.constant([[2,2,2],[3,3,3],[7,7,7]])

In [17]:
matrix_a + matrix_b

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 3,  4,  5],
       [ 7,  8,  9],
       [14, 15, 16]], dtype=int32)>

In [18]:
add(matrix_a, matrix_b)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 3,  4,  5],
       [ 7,  8,  9],
       [14, 15, 16]], dtype=int32)>

In [20]:
# multiplication fo two matrix is like this form
def multiplication(a,b):
    return tf.matmul(a,b)

In [21]:
multiplication(matrix_a, matrix_b)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 29,  29,  29],
       [ 65,  65,  65],
       [101, 101, 101]], dtype=int32)>

In [25]:
# and here we have subtract 

a = tf.constant([5])
b = tf.constant([2])
c = tf.add(a,b)
d = tf.subtract(a,b)

c, d

(<tf.Tensor: shape=(1,), dtype=int32, numpy=array([7], dtype=int32)>,
 <tf.Tensor: shape=(1,), dtype=int32, numpy=array([3], dtype=int32)>)

In [28]:
# variables in tensorflow are really important and we can use them in the calculation in this way

v = tf.Variable(0)

def increase_by_two(v):
    return tf.add(v,1)

for i in range(3):
    v = increase_by_two(v)
    print(v)


tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)
